set(_root "${CMAKE_CURRENT_BINARY_DIR}/ScriptTemporaryConfig-${TEST_MODE}")
file(MAKE_DIRECTORY "${_root}")
set(_temp "${_root}")
if(TEST_MODE STREQUAL "create-failure")
    set(_temp "${_root}/missing")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E env
    "TMPDIR=${_temp}" "TMP=${_temp}" "TEMP=${_temp}" "TEMPDIR=${_temp}"
    "${TEST_EXECUTABLE}" "${TEST_MODE}"
    RESULT_VARIABLE _result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
file(REMOVE_RECURSE "${_root}")
if(NOT _result STREQUAL "86")
    message(FATAL_ERROR "Expected abort/SIGABRT; got '${_result}'\n${_stdout}\n${_stderr}")
endif()
if(TEST_MODE STREQUAL "create-failure")
    set(_expected "Cannot (locate|create) temporary directory")
elseif(TEST_MODE STREQUAL "file-cleanup-failure")
    set(_expected "Cannot remove temporary file")
elseif(TEST_MODE STREQUAL "directory-cleanup-failure")
    set(_expected "Cannot remove temporary directory")
elseif(TEST_MODE STREQUAL "write-failure")
    set(_expected "Cannot (write|close) temporary file")
endif()
if(NOT _stderr MATCHES "Script: temporary runtime config failure: ${_expected}")
    message(FATAL_ERROR "Expected diagnostic before abort\n${_stderr}")
endif()
