add_subdirectory("Resource.Tests")
add_subdirectory("Filesystem.Tests")
add_subdirectory("Core.Tests")
add_subdirectory("Physics.Tests")
add_subdirectory("RenderInFlight.Tests")
add_subdirectory("WorldExecutionOrder.Tests")
add_subdirectory("WorldSerialization.Tests")
add_subdirectory("RenderThread.Tests")
add_subdirectory("RenderResource.Tests")
add_subdirectory("Lifecycle.Tests")
add_subdirectory("ImGuiPacket.Tests")
add_subdirectory("RenderFeature.Tests")
add_subdirectory("RenderCommandExtraction.Tests")
