function(aether_target_add_dependency target dep visibility)
    if(NOT visibility)
        set(visibility PRIVATE)
    endif()
    if(TARGET ${dep})
        target_link_libraries(${target} ${visibility} ${dep})
    else()
        message(FATAL_ERROR "Dependency '${dep}' is not a valid target!")
    endif()
endfunction()